// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPW5C-1Q1ZnJjFPpS5pMUo088ZEmxQ1mg',
    appId: '1:176016784823:web:92bfe6d891542a69327c32',
    messagingSenderId: '176016784823',
    projectId: 'weatherapp-87a39',
    authDomain: 'weatherapp-87a39.firebaseapp.com',
    storageBucket: 'weatherapp-87a39.firebasestorage.app',
    measurementId: 'G-28CN6B180T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_BLurf5HKQkskwPuKg32Iz3vd6fcasL8',
    appId: '1:176016784823:android:a4808e6085244a27327c32',
    messagingSenderId: '176016784823',
    projectId: 'weatherapp-87a39',
    storageBucket: 'weatherapp-87a39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqL96IQAT05U5xL5hTnF8J4KfD5c1xkug',
    appId: '1:176016784823:ios:9937ee287bb30c9e327c32',
    messagingSenderId: '176016784823',
    projectId: 'weatherapp-87a39',
    storageBucket: 'weatherapp-87a39.firebasestorage.app',
    iosBundleId: 'com.example.newWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqL96IQAT05U5xL5hTnF8J4KfD5c1xkug',
    appId: '1:176016784823:ios:9937ee287bb30c9e327c32',
    messagingSenderId: '176016784823',
    projectId: 'weatherapp-87a39',
    storageBucket: 'weatherapp-87a39.firebasestorage.app',
    iosBundleId: 'com.example.newWeatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPW5C-1Q1ZnJjFPpS5pMUo088ZEmxQ1mg',
    appId: '1:176016784823:web:c42a6eeb2b2a4d02327c32',
    messagingSenderId: '176016784823',
    projectId: 'weatherapp-87a39',
    authDomain: 'weatherapp-87a39.firebaseapp.com',
    storageBucket: 'weatherapp-87a39.firebasestorage.app',
    measurementId: 'G-6G5VSLMEQ5',
  );
}
